name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:21

    env:
      SSL_KEYSTORE_PATH: ${{ secrets.SSL_KEYSTORE_PATH }}
      SSL_KEYSTORE_PASSWORD: ${{ secrets.SSL_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build, test and package application
        run: ./mvnw clean test package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 60
